### ISSUE TITLE
Can't download, upload or delete files using the web UI

### ISSUE THREAD

**Issue by luiztauffer** [aws-solutions/simple-file-manager-for-amazon-efs#208]
**Describe the bug**

I can't upload, download or delete files. It gives me an error message: `File was unable to be uploaded successfully. Check API logs.`
When trying to download, it just gets stuck in the download message...

I managed to deploy the stack successfully, and logged in the web UI. I can see folders and files created by other processes (EC2 machines) in the file system.

**Please complete the following information about the solution:**
- [x] Version: (SO0145) Simple File Manager for Amazon EFS Solution Auth v1.5.5
- [x] Region: us-east-2
- [x] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by simonkrol** [comment]
Hi @luiztauffer, 

That is very strange, is this happening with the default admin user created upon deploying the stack? If so, have you made any changes to the Cognito user pool or Cognito administrator group?

Let me know,
Simon

**Comment by luiztauffer** [comment]
Hey @simonkrol , yes it happens with the default admin user. I haven't touched anything in Cognito, anything I should try and check out there?

**Comment by leon-mrks** [comment]
Hey Guys!

Just wanted to hop in and say: same here
Even after creating a new EFS instance the errors still appear.

- Creating a folder: `Could not create directory. Check API logs.`
- Uploading a file: `File was unable to be uploaded successfully. Check API logs.`
- Deleting a file: `File was unable to be deleted successfully. Check API logs.`

Where can I find said "API logs"? maybe it helps to have a look.
In CloudFront nothing useful showed up.

**Comment by simonkrol** [comment]
Hi @leon-mrks,
You can check the file manager lambda to access it's CloudWatch logs. 

To access the logs:
1. Navigate to the CloudFormation console
2. Look for the stack created for your EFS. It should have a name similar to {$SFMSTACKNAME}-ManagedResources-{$EFSName}
3. Select the resources tab and click the Physical ID for the resource with the logical id: ManagedAccessPointFunction (This should bring you to the lambda console)
4. On the lambda console, select the Monitor tab, and click View CloudWatch logs to bring you to the log group for your file system.

Please let me know if you find anything that might help with debugging,
Thanks,
Simon

**Comment by leon-mrks** [comment]
Thanks @simonkrol for the explanation!

Here is an example upload error:
```
1. START RequestId: <id_detacted> Version: $LATEST

2. {'operation': 'upload', 'path': '/mnt/efs', 'chunk_data': {'dzchunkindex': 0, 'dztotalfilesize': 31959, 'dzchunksize': 1000000, 'dztotalchunkcount': 1, 'dzchunkbyteoffset': 0, 'content': ... }

3. Could not write to file: [Errno 13] Permission denied: '/mnt/efs/example.txt'

4. END RequestId: <id_detacted>
```

The `make_dir` and `delete` operations do not log any errors though.

**Comment by simonkrol** [comment]
Hi @leon-mrks,
Thanks for your patience here, if you check the File system that you're running into issues here on, is there anything listed under `File system policy`?

Let me know,
Simon

**Comment by simonkrol** [comment]
Hi @leon-mrks,
I'm going to close this for now, please re-open if you continue to run into this issue and can provide some more details.

Thanks,
Simon

**Comment by FranciscoCross** [comment]
I’m facing the same issue. Currently, when I set it to false to create a Lambda that handles a specific EFS with an access point, I later find that I can't view any files, create directories, or upload files. After testing and verifying different configurations, I’ve been able to resolve the issue.

I tried creating an EFS in the default VPC of the account where I’m implementing the viewer, and it worked. But why didn't my previous attempts work? Well, it’s because the security group (SG) for the Lambda that is created for the EFS in the default VPC allows everything in its inbound rules. I’ve attached a screenshot for reference.

The Lambdas that weren't working only allow the VPC’s CIDR in the inbound rules. Once I allowed all traffic, everything worked. The question is, though, whether this is a good practice or not. What would be the ideal solution? If the Lambda accessing this EFS is another Lambda, how can I configure a security group (SG) for this scenario, considering that the other Lambda doesn’t have a private IP?
![image](https://github.com/user-attachments/assets/9312b2f0-6edf-47d4-b643-08ae69752be9)
